name: go
on:
  workflow_call:
    inputs:
      setup_terraform:
        type: boolean
        description: "Install Terraform"
        default: false
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ['stable']
    steps:
      # Checkout repo to GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go}}

      # Install Terraform
      - name: Setup Terraform
        if: ${{ inputs.setup_terraform }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      # Test
      - name: Go Test
        run: make
